# Build environment
FROM node:alpine as build
WORKDIR /ngeo-ui
COPY . /ngeo-ui/
RUN ["yarn", ""]
RUN ["yarn", "build"]

# production environment
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /ngeo-ui/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]